config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :rents
    resources :cars
  end

  resources :rents # , only: [:new, :create, :show]

  root 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
# frozen_string_literal: true

class Car < ApplicationRecord
  belongs_to :category, optional: false

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :rented, presence: true, if: -> { rented.nil? }
  validates :url_image, presence: true

  has_many :rents

  scope :rented, -> { where(rented: true) }
  scope :not_rented, -> { where(rented: false) } # fazer o test model
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  has_many :cars
end

app/models/rent.rb
# frozen_string_literal: true

class Rent < ApplicationRecord
  before_validation :calculate_price_total, on: :create

  belongs_to :car, required: true
  validates :name, presence: true
  validates :date_start, presence: true
  validates :date_end, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }

  def calculate_price_total
    price_total = 0.00
    price_total = CalculatePriceService.new(car.price, date_start, date_end).call
    self.price = price_total
  end
end

app/controllers/admin/cars_controller.rb
# frozen_string_literal: true

module Admin
  class CarsController < ApplicationController
    before_action :set_car, only: %i[show update edit]

    def index
      @cars = Car.all
    end

    def show; end

    def new
      @car = Car.new
    end

    def edit; end

    def create
      @car = Car.new(car_params)
      respond_to do |format|
        if @car.save
          format.html { redirect_to admin_car_url(@car), notice: 'Car was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      if @car.update(car_params)
        flash[:notice] = 'Car update successfull.'
        redirect_to admin_car_url(@car)
      else
        render :edit
      end
    end

    private

    def car_params
      params.require(:car).permit(:category_id, :name, :price, :rented, :url_image)
    end

    def set_car
      @car = Car.find(params[:id])
    end
  end
end

app/controllers/admin/rents_controller.rb
# frozen_string_literal: true

module Admin
  class RentsController < ApplicationController
    before_action :set_rent, only: %i[show update edit]

    def index
      @rents = Rent.all
    end

    def show; end

    def new
      @rent = Rent.new
    end

    def edit; end

    def create
      @rent = Rent.new(rent_params)

      respond_to do |format|
        if @rent.save
          format.html { redirect_to admin_rent_url(@rent), notice: 'Rental was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      if @rent.update(rent_params)
        flash[:notice] = 'Rent update successfull.'
        redirect_to admin_rent_url(@rent)
      else
        render :edit
      end
    end

    private

    def rent_params
      params.require(:rent).permit(:car_id, :name, :date_start, :date_end)
    end

    def set_rent
      @rent = Rent.find(params[:id])
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  require 'webpacker/version'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @cars = Car.not_rented
  end
end

app/controllers/rents_controller.rb
# frozen_string_literal: true

class RentsController < ApplicationController
  def new
    @rent = Rent.new
    @car = Car.find(params[:car_id])
  end

  def create
    @rent = Rent.new(rent_params)

    respond_to do |format|
      if @rent.save
        format.html { redirect_to @rent, notice: 'Rental was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @rent = Rent.find(params[:id])
  end

  private

  def rent_params
    params.require(:rent).permit(:car_id, :name, :date_start, :date_end)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/rents_helper.rb
# frozen_string_literal: true

module RentsHelper
end

app/views/admin/cars/_form.html.erb
<%= form_for [:admin, @car] do |f| %>
  <% if car.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>
    <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :category, class: 'label'  %>
    <div class="control">
      <div class="select">
        <%= f.select(:category_id, Category.all.map { |c| [c.name, c.id]}, :prompt => 'Select') %>
      </div>
    </div>
  </div>  

  <div class="field">
    <%= f.label :name, class: 'label'  %>
    <div class="control">
      <%= f.text_field :name, class: "input"  %>
    </div>
  </div>

  <div class="field">
    <%= f.label :price, class: 'label'  %>
    <div class="control">
      <%= f.text_field :price, class: "input"  %>
    </div>
  </div>

  <div class="field">
    <%# <%= f.label :rented, class: 'label' %>
    <div class="control">
      <%= f.check_box :rented, {:class => "myclass", :style => "mystyle"}, "checked-value", "unchecked-value" %>
      <label for="rented">Rented</label>
    </div>
  </div>

  <div class="field">
    <%= f.label :url_image, class: 'label'  %>
    <div class="control">
      <%= f.text_field :url_image, class: "input"  %>
    </div>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', admin_cars_path, class: 'btn btn-outline-primary btn-sm' %>
    </div>
  </div>

 <% end %>

app/views/admin/cars/edit.html.erb
<h3 class='title'>Edit Car</h3>

<%= render 'form', car: @car %>

app/views/admin/cars/index.html.erb
<div class="table-responsive table-striped caption-top">
  <div style="display: flex; justify-content: space-between">
    <caption>List of cars</caption>
    <%= link_to 'New Car', new_admin_car_path, class: "btn btn-outline-info btn-sm" %>
  </div>
  <table class="table align-middle">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Car</th>
        <th scope="col">Price</th>
        <th scope="col">Rented</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @cars.each do |car| %>
      <tr class="align-bottom">
        <td><%= car.id %></td>
        <td><%= car.name %></td>
        <td><%= car.price %></td>
        <td><%= car.rented %></td>
        <td><%= link_to 'Show', admin_car_path(car), class: "btn btn-outline-info btn-sm" %></td>
        <td><%= link_to 'Edit', edit_admin_car_path(car), class: "btn btn-outline-primary btn-sm" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/cars/new.html.erb
<h3 class='title'>New Car</h1>

<%= render 'form', car: @car %>

app/views/admin/cars/show.html.erb
<p id="notice"><%= notice %></p>

<div class="content">
<h3>Rent</h3>

<p>
  <strong>Car</strong>
  <%= @car&.category&.name %> 
</p>

<p>
  <strong>Name:</strong>
  <%= @car.name %> 
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@car&.price, precision: 2) %> 
</p>

<p>
  <strong>Rented:</strong>
  <%= @car.rented %> 
</p>

<p>
 <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <div class="row align-items-center">
      <div class="card shadow-sm" >
        <div class="car-image">
          <img alt="image" class="bd-placeholder-img card-img-top" src="<%= image_path(@car&.url_image) %>">
        </div>

        <div class="card-body">
          <p class="card-text"></p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</p>


<%= link_to 'Edit', edit_admin_car_path(@car), class: "btn btn-outline-primary btn-sm" %> |
<%= link_to 'Back', admin_cars_path, class: "btn btn-primary btn-sm" %>

</div>

app/views/admin/rents/_form.html.erb
<%= form_for([:admin, @rent]) do |f| %>
  <% if rent.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(rent.errors.count, "error") %> prohibited this rent from being saved:</h2>
    <ul>
      <% rent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :car, class: 'label'  %>
    <div class="control">
     <%= f.select(:car_id, Car.all.map { |c| [c.name, c.id]}, :prompt => 'Select') %>
    </div>
  </div>

  <div class="field">
    <%= f.label :name, class: 'label'  %>
    <div class="control">
      <%= f.text_field :name, class: "input"  %>
    </div>
  </div>

  <div class="field">
    <%= f.label :date_start, class: 'label'  %>
    <div class="control">
      <%= f.text_field :date_start, class: "input"  %>
    </div>
  </div>

  <div class="field">
    <%= f.label :date_end, class: 'label'  %>
    <div class="control">
      <%= f.text_field :date_end, class: "input"  %>
    </div>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', admin_rents_path, class: 'btn btn-outline-primary btn-sm' %>
    </div>
  </div>

 <% end %>

app/views/admin/rents/edit.html.erb
<h3 class='title'>Edit Rent</h3>

<%= render 'form', rent: @rent %>

app/views/admin/rents/index.html.erb
<div class="table-responsive table-striped caption-top">
  <caption>List of cars</caption>
  <table class="table align-middle">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Car</th>
        <th scope="col">Name</th>
        <th scope="col">Date Start</th>
        <th scope="col">Date End</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @rents.each do |rent| %>
      <tr class="align-bottom">
        <td><%= rent&.id %></td>
        <td><%= rent&.car.name %></td>
        <td><%= rent.name %></td>
        <td><%= rent.date_start %></td>
        <td><%= number_to_currency(rent&.price, precision: 2) %> </td>
        <td><%= link_to 'Show', admin_rent_path(rent), class: "btn btn-outline-info btn-sm" %></td>
        <td><%= link_to 'Edit', edit_admin_rent_path(rent), class: "btn btn-outline-primary btn-sm" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/rents/new.html.erb
<h3 class='title'>New Rent</h3>

<%= render 'form', rent: @rent %>

app/views/admin/rents/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Rent</h3>

<p>
  <strong>Car</strong>
  <%= @rent&.car&.name %> 
</p>

<p>
  <strong>Name:</strong>
  <%= @rent.name %> 
</p>

<p>
  <strong>Date Start:</strong>
  <%= @rent.date_start %> 
</p>

<p>
  <strong>Date End:</strong>
  <%= @rent.date_end %> 
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@rent&.price, precision: 2) %> 
</p>

<%= link_to 'Edit', edit_admin_rent_path(@rent), class: "btn btn-outline-primary btn-sm" %> |
<%= link_to 'Back', admin_rents_path, class: "btn btn-primary btn-sm"  %>

app/views/home/_footer.html.erb
<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="../getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>

app/views/home/_header.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">Rent a Car</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Rent a Car</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

app/views/home/_main.html.erb
<style>
  .car-image {
    /* min-height: 280 px; */
  }
</style>

<main>
    <%# <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Album example</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section> %>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      
      <% @cars.each do |car| %>
        
        <div class="col">
          <div class="card shadow-sm" >
            <div class="car-image">
              <img alt="image" class="bd-placeholder-img card-img-top" src="<%= image_path(car&.url_image) %>">
            </div>

            <div class="card-body">
              <p class="card-text"><%= car&.name %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%# <button type="button" class="btn btn-sm btn-outline-secondary">Reserve</button> %>
                  <%= link_to "Reserve", new_rent_path(car_id: car&.id), class: 'btn btn-sm btn-outline-secondary'  %>
                </div>
                <small class="text-muted"><%= number_to_currency(car.price, precision: 2) %></small>
              </div>
            </div>
          </div>
        </div>

      <% end %>

      </div>
    </div>
  </div>
</main>

<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

app/views/home/index.html.erb
   
<%= render 'header' %>
<%= render 'main' %>
<%= render 'footer' %>

<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rent a car</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet"> %>

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

  </head>

  <body>
    <div class="content">
      <%= yield %>
    </div>
  </body>

</html>

app/views/rents/new.html.erb
<%= render '/home/header' %>

<main>
  <%= form_for(@rent) do |f| %>
    <%= f.hidden_field :car_id, value: @car.id %>
    <% if @rent.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@rent.errors.count, "error") %> prohibited this rent from being saved:</h2>
        <ul>
          <% @rent.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <div>
    <% end %>
  
    <div class="container">
      <div class="row align-items-center">
        <div class="col">
          <div class="card shadow-sm" >
              <div class="car-image">
                <img alt="image" class="bd-placeholder-img card-img-top" src="<%= image_path(@car&.url_image) %>">
              </div>

              <div class="card-body">
                <p class="card-text"><%= @car&.name %></p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <%# <button type="button" class="btn btn-sm btn-outline-secondary">Reserve</button> %>
                    <%#= link_to "Reserve", new_rent_path(car_id: @car&.id), class: 'btn btn-sm btn-outline-secondary'  %>
                  </div>
                  <small class="text-muted"><%= number_to_currency(@car.price, precision: 2) %></small>
                </div>
              </div>
            </div>
        </div>
        <div class="col">

          <div class="field">
            <%= f.label :name, class: 'label'  %>
            <div class="control">
              <%= f.text_field :name, class: "input"  %>
            </div>
          </div>

          <div class="field">
            <%= f.label :date_start, class: 'label'  %>
            <div class="control">
              <%= f.date_field :date_start, class: "input"  %>
            </div>
          </div>    

          <div class="field">
            <%= f.label :date_end, class: 'label'  %>
            <div class="control">
              <%= f.date_field :date_end, class: "input"  %>
            </div>
          </div>          

          <div class="field is-grouped">
            <div class="control">
              <%= f.submit "Rent", class: 'btn btn-primary' %>
              <%= link_to 'Back', root_path, class: 'btn btn-light' %>
            </div>
          </div>
        </div>
      </div>
    </div>
   

  <% end %>
</main>


<%= render '/home/footer' %>

<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

app/views/rents/show.html.erb
<div class="container">
  <div class="row align-items-center">
    <div class="card shadow-sm" >
      <div class="car-image">
        <img alt="image" class="bd-placeholder-img card-img-top" src="<%= image_path(@rent&.car&.url_image) %>">
      </div>

      <div class="card-body">
        <p class="card-text"><%= @rent&.car&.name %></p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <%# <button type="button" class="btn btn-sm btn-outline-secondary">Reserve</button> %>
            <%#= link_to "Reserve", new_rent_path(car_id: car&.id), class: 'btn btn-sm btn-outline-secondary'  %>
          </div>
          <small class="text-muted"><%= number_to_currency(@rent&.price, precision: 2) %></small>
        </div>
      </div>
    </div>
  </div>
  <h4>Você alugou um <%= @rent&.car&.name %> no valor de <%= number_to_currency(@rent&.price, precision: 2) %></h4>
  <h5>pelo o período de <%= @rent&.date_start %> á <%= @rent&.date_end %></h5>
</div>